const fs = require('fs');
const path = require('path');

function safeString(value) {
  return typeof value === 'string' ? value : (value == null ? '' : String(value));
}

module.exports = {
  onPreBuild({ constants }) {
    const functionsDir = constants?.FUNCTIONS_SRC || '(unknown)';
    console.log(`[#hmjg] Active functions directory → ${functionsDir}`);

    const payload = {
      ADMIN_IDENTITY_URL: safeString(process.env.ADMIN_IDENTITY_URL || process.env.HMJ_ADMIN_IDENTITY_URL || ''),
    };

    const lines = [
      '// Generated by Netlify build (hmjg admin bootstrap).',
      '(function(){',
      '  var env = ' + JSON.stringify(payload) + ';',
      '  window.__HMJ_ADMIN_ENV = env;',
      '  if (env.ADMIN_IDENTITY_URL) { window.ADMIN_IDENTITY_URL = env.ADMIN_IDENTITY_URL; }',
      '})();',
      '',
    ];

    const outFile = path.join(process.cwd(), 'admin', '__env.js');
    fs.mkdirSync(path.dirname(outFile), { recursive: true });
    fs.writeFileSync(outFile, lines.join('\n'));
    console.log(`[#hmjg] Admin env injected → ${outFile}`);
  }
};
