// Generated by Netlify build (hmjg admin bootstrap).
(function(){
  var env = {"ALWAYS_ADMIN_EMAILS":"","FORCE_ADMIN_KEY":"","ADMIN_IDENTITY_URL":""};
  window.__HMJ_ADMIN_ENV = env;
  if (typeof env.ALWAYS_ADMIN_EMAILS === "string") { window.ALWAYS_ADMIN_EMAILS = env.ALWAYS_ADMIN_EMAILS; }
  if (typeof env.FORCE_ADMIN_KEY === "string") { window.FORCE_ADMIN_KEY = env.FORCE_ADMIN_KEY; }
  if (env.ADMIN_IDENTITY_URL) { window.ADMIN_IDENTITY_URL = env.ADMIN_IDENTITY_URL; }
})();
