// Generated by Netlify build (hmjg admin bootstrap).
(function(){
  var env = {"ADMIN_IDENTITY_URL":""};
  window.__HMJ_ADMIN_ENV = env;
  if (env.ADMIN_IDENTITY_URL) { window.ADMIN_IDENTITY_URL = env.ADMIN_IDENTITY_URL; }
})();
