backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

publish_mode: editorial_workflow

site_url: "https://www.hmj-global.com"
logo_url: "/images/logo.png"

collections:
  - name: "jobs"
    label: "Jobs"
    label_singular: "Job"
    editor:
      preview: false
    files:
      - file: "data/jobs.json"
        label: "All Jobs"
        name: "jobsfile"
        description: "Edit all job entries here. This file powers jobs.html."
        fields:
          - label: "Jobs"
            name: "jobs"
            widget: "list"
            collapsed: true
            summary: "{{fields.title}} — {{fields.locationText}} ({{fields.status}})"
            fields:
              - { label: "ID (unique, used as anchor)", name: "id", widget: "string" }
              - { label: "Published", name: "published", widget: "boolean", default: true }
              - { label: "Title", name: "title", widget: "string" }
              - label: "Status"
                name: "status"
                widget: "select"
                options:
                  - { label: "Live", value: "live" }
                  - { label: "Interviewing", value: "interviewing" }
                  - { label: "Closed", value: "closed" }
                default: "live"
              - label: "Section (Board)"
                name: "section"
                widget: "select"
                options:
                  - { label: "Data Centre — Commercial", value: "commercial" }
                  - { label: "Data Centre — Engineering & Management", value: "dc" }
                  - { label: "Substations, Power & Energy", value: "substations" }
                  - { label: "Life Sciences & Pharma", value: "pharma" }
                  - { label: "ICT & Commissioning", value: "ict" }
                default: "dc"
              - label: "Discipline"
                name: "discipline"
                widget: "select"
                options:
                  - "Data Centre"
                  - "Life Sciences"
                  - "Pharma"
                  - "Substation"
                default: "Data Centre"
              - label: "Employment Type"
                name: "type"
                widget: "select"
                options:
                  - { label: "Permanent", value: "permanent" }
                  - { label: "Contract", value: "contract" }
                default: "permanent"
              - label: "Location Code (filter)"
                name: "locationCode"
                widget: "select"
                options:
                  - { label: "All (not for jobs)", value: "all" }
                  - { label: "Amsterdam, Netherlands", value: "amsterdam" }
                  - { label: "Dublin, Ireland", value: "dublin" }
                  - { label: "Eemshaven, Netherlands", value: "eemshaven" }
                  - { label: "Espoo, Finland", value: "espoo" }
                  - { label: "Frankfurt, Germany", value: "frankfurt" }
                  - { label: "Groningen, Netherlands", value: "groningen" }
                  - { label: "Helsinki, Finland", value: "helsinki" }
                  - { label: "London, UK", value: "london" }
                  - { label: "Macclesfield, UK", value: "macclesfield" }
                  - { label: "UK (Various)", value: "uk" }
                  - { label: "Europe (Travel)", value: "europe" }
                default: "uk"
              - { label: "Location Text (shown)", name: "locationText", widget: "string" }
              - { label: "Keywords (searchable)", name: "keywords", widget: "text", required: false }
              - { label: "Overview", name: "overview", widget: "text", required: false }
              - label: "Responsibilities"
                name: "responsibilities"
                widget: "list"
                required: false
                field: { label: "Item", name: "item", widget: "string" }
              - label: "Requirements"
                name: "requirements"
                widget: "list"
                required: false
                field: { label: "Item", name: "item", widget: "string" }
              - { label: "Apply URL (optional)", name: "applyUrl", widget: "string", required: false }
