backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

publish_mode: editorial_workflow
locale: en

# We are editing a single JSON file (data/jobs.json) that contains:
# { "jobs": [ { ...job fields... } ] }
collections:
  - name: "jobsData"
    label: "Jobs Data"
    label_singular: "Job"
    editor:
      preview: false
    files:
      - file: "data/jobs.json"
        name: "jobsFile"
        label: "Jobs Data"
        description: "Single JSON file powering /jobs.html."
        format: "json"
        fields:
          - label: "Jobs"
            name: "jobs"
            widget: "list"
            collapsed: true
            summary: "{{fields.title}} — {{fields.locationText}} ({{fields.status}})"
            fields:
              - { label: "ID (unique)", name: "id", widget: "string", hint: "e.g. mep-qs-dublin" }
              - { label: "Published", name: "published", widget: "boolean", default: true }
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Status", name: "status", widget: "select", options: ["live","on-hold","closed"], default: "live" }
              - { label: "Section", name: "section", widget: "select", options: ["commercial","mep","civils","pharma","data-centre","power","other"], default: "commercial" }
              - { label: "Discipline", name: "discipline", widget: "string", required: false }
              - { label: "Type", name: "type", widget: "select", options: ["permanent","contract","temporary","internship"], default: "permanent" }
              - { label: "Location Code", name: "locationCode", widget: "string", hint: "Short code, e.g. dublin / london" }
              - { label: "Location Text", name: "locationText", widget: "string", hint: "What users see, e.g. Dublin, IE" }
              - { label: "Keywords (CSV)", name: "keywords", widget: "string", required: false, hint: "Comma-separated" }
              - { label: "Overview", name: "overview", widget: "text", required: false }
              - label: "Responsibilities"
                name: "responsibilities"
                widget: "list"
                required: false
                field: { label: "Item", name: "item", widget: "string" }
              - label: "Requirements"
                name: "requirements"
                widget: "list"
                required: false
                field: { label: "Item", name: "item", widget: "string" }
              - { label: "Apply URL", name: "applyUrl", widget: "string", required: false }
