create table if not exists public.short_links (
  id bigint generated by default as identity primary key,
  slug text not null unique
    check (slug = lower(slug))
    check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  destination_url text not null
    check (destination_url ~* '^https?://'),
  title text,
  created_at timestamptz not null default timezone('utc', now()),
  created_by text,
  created_by_email text,
  is_active boolean not null default true,
  click_count integer not null default 0,
  last_used_at timestamptz
);

create index if not exists short_links_created_at_idx
  on public.short_links (created_at desc);

create index if not exists short_links_active_created_at_idx
  on public.short_links (is_active, created_at desc);

alter table public.short_links enable row level security;

comment on table public.short_links is
  'HMJ branded short links created from the admin dashboard. Public redirects should go through Netlify Functions rather than direct browser access.';
