# netlify.toml
[build]
  publish = "."                    # (whatever your site root is)
  functions = "admin/functions"    # <-- IMPORTANT: points to your folder



# netlify.toml
[[redirects]]
  from = "/admin/functions/*"
  to   = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/admin/*"
  to   = "/admin-v2/admin/:splat"
  status = 200

